pipeline{
    agent any

    stages{
        stage('zip the file'){
            steps{
                sh 'zip -r ansible-dev_${BUILD_ID}.zip * --exclude Jenkinsfile'
            }
        }
        stage('upload artifact to Jfrog'){
            steps{
            sh 'curl -uadmin:AP8JrETP4pkpQEdKpLHxJwhVieo -T \
            ansible-dev_${BUILD_ID}.zip\
            "http://34.229.74.74:8081/artifactory/ansible/ansible-dev_${BUILD_ID}.zip"'
            }
        }
        stage('publish to ansible server'){
            steps{
                sshPublisher(publishers: [sshPublisherDesc(configName: 'AnsibleServer', \
                transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: \
                'ls', execTimeout: 120000, flatten: false, makeEmptyDirs: false, \
                noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: \
                '.', remoteDirectorySDF: false, removePrefix: '', \
                sourceFiles: 'ansible-dev_${BUILD_ID.}zip')], usePromotionTimestamp: false, \
                useWorkspaceInPromotion: false, verbose: false)])
            }
    
        }   
    }
}