pipeline{
    agent any

    stages{
        stage('zip the file'){
            steps{
                sh 'zip -r ansible-dev_${BUILD_ID}.zip * --exclude Jenkinsfile'
                sh 'ls -l'
            }
        }
    }
}